--liquibase formatted sql
--changeset vivek.vadadoriya@invitationhomes.com:EDCOR_834_added_resolution_type_filter.sql

create or replace view VW_SPRINT_VELOCITY(
	PROJECT_KEY,
    PROJECT_NAME,
    SPRINT_ID,
    SPRINT_NARRATIVE,
    EXECUTIVE_SUMMARY,
    SPRINT_NAME,
    TOTAL_POINTS,
    TOTAL_TICKETS,
    AVG_TICKET_SIZE,
    TOTAL_STORY_POINTS,
    TOTAL_STORY_TICKETS,
    AVG_STORY_SIZE,
    TOTAL_BUG_POINTS,
    TOTAL_BUG_TICKETS,
    AVG_BUG_SIZE,
    TOTAL_TASK_POINTS,
    TOTAL_TASK_TICKETS,
    AVG_TASK_SIZE,
    TOTAL_SPIKE_POINTS,
    TOTAL_SPIKE_TICKETS,
    AVG_SPIKE_SIZE,
    AVG_LAST_3_SPRINT_POINTS,
    CARRY_OVER_TICKET,
    CARRY_OVER_POINTS,
    TOTAL_TICKETS_PROJECT,
    TOTAL_TICKETS_KLO,
    TOTAL_TICKETS_BAU,
    TOTAL_TICKETS_WORK_TYPE_EMPTY,
    TOTAL_STORY_POINTS_PROJECT,
    TOTAL_STORY_POINTS_KLO,
    TOTAL_STORY_POINTS_BAU,
    TOTAL_STORY_POINTS_WORK_TYPE_EMPTY
) as
WITH BASE_METRICS AS
(
  SELECT DISTINCT SM.PROJECT_KEY AS PROJECT_KEY,
         SM.PROJECT_NAME AS PROJECT_NAME,
         SM.SPRINT_ID AS SPRINT_ID,
         IM.SPRINT_NARRATIVE AS SPRINT_NARRATIVE,
         IM.EXECUTIVE_SUMMARY AS EXECUTIVE_SUMMARY,
         SM.SPRINT_NAME AS SPRINT_NAME,
         SUM(CASE WHEN IM.COMPLETED_POINTS IS NOT NULL THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_POINTS,
         SM.TOTAL_TICKETS AS TOTAL_TICKETS,
         ZEROIFNULL(TOTAL_POINTS / NULLIFZERO (SM.TOTAL_TICKETS))::NUMBER(38,2) AS AVG_TICKET_SIZE,
         SUM(CASE WHEN IM.ISSUE_TYPE = 'Story' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS TOTAL_STORY_POINTS,
         SM.TOTAL_STORY_TICKETS AS TOTAL_STORY_TICKETS,
         ZEROIFNULL(TOTAL_STORY_POINTS / NULLIFZERO (SM.TOTAL_STORY_TICKETS))::NUMBER(38,2) AS AVG_STORY_SIZE,
         SUM(CASE WHEN IM.ISSUE_TYPE = 'Bug' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS TOTAL_BUG_POINTS,
         SM.TOTAL_BUG_TICKETS AS TOTAL_BUG_TICKETS,
         ZEROIFNULL(TOTAL_BUG_POINTS / NULLIFZERO (SM.TOTAL_BUG_TICKETS))::NUMBER(38,2) AS AVG_BUG_SIZE,
         SUM(CASE WHEN IM.ISSUE_TYPE = 'Task' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS TOTAL_TASK_POINTS,
         SM.TOTAL_TASK_TICKETS AS TOTAL_TASK_TICKETS,
         ZEROIFNULL(TOTAL_TASK_POINTS / NULLIFZERO (SM.TOTAL_TASK_TICKETS))::NUMBER(38,2) AS AVG_TASK_SIZE,
         SUM(CASE WHEN IM.ISSUE_TYPE = 'Spike' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS TOTAL_SPIKE_POINTS,
         SM.TOTAL_SPIKE_TICKETS AS TOTAL_SPIKE_TICKETS,
         ZEROIFNULL(TOTAL_SPIKE_POINTS / NULLIFZERO (SM.TOTAL_SPIKE_TICKETS))::NUMBER(38,2) AS AVG_SPIKE_SIZE,
         SUM(CASE WHEN IM.IS_CARRY_OVER THEN 1 ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS CARRY_OVER_TICKET,
         SUM(CASE WHEN IM.IS_CARRY_OVER THEN IM.STORY_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID,SM.PROJECT_KEY) AS CARRY_OVER_POINTS
  FROM ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM
    LEFT JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM ON IM.SPRINT_ID = SM.SPRINT_ID AND SM.PROJECT_KEY = IM.PROJECT_KEY
  WHERE IM.BOARD_TYPE = 'Sprints'
),
work_type_metrics AS
(
  SELECT im.PROJECT_KEY,
         im.PROJECT_NAME,
         im.SPRINT_ID,
         im.SPRINT_NAME,
         im.SPRINT_NARRATIVE,
         im.EXECUTIVE_SUMMARY,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'project' AND ((im.ISSUE_STATUS = 'Done' AND im.ISSUE_RESOLUTION = 'Done') OR im.ISSUE_STATUS = 'Ready For Deployment') THEN 1 ELSE 0 END)::NUMBER(38,2) AS total_tickets_project,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'klo' AND ((im.ISSUE_STATUS = 'Done' AND im.ISSUE_RESOLUTION = 'Done') OR im.ISSUE_STATUS = 'Ready For Deployment') THEN 1 ELSE 0 END)::NUMBER(38,2) AS total_tickets_klo,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'bau' AND ((im.ISSUE_STATUS = 'Done' AND im.ISSUE_RESOLUTION = 'Done') OR im.ISSUE_STATUS = 'Ready For Deployment') THEN 1 ELSE 0 END)::NUMBER(38,2) AS total_tickets_bau,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) IS NULL AND ((im.ISSUE_STATUS = 'Done' AND im.ISSUE_RESOLUTION = 'Done') OR im.ISSUE_STATUS = 'Ready For Deployment') THEN 1 ELSE 0 END)::NUMBER(38,2) AS total_tickets_work_type_empty,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'project' THEN im.COMPLETED_POINTS ELSE 0 END)::NUMBER(38,2) AS total_story_points_project,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'klo' THEN im.COMPLETED_POINTS ELSE 0 END)::NUMBER(38,2) AS total_story_points_klo,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'bau' THEN im.COMPLETED_POINTS ELSE 0 END)::NUMBER(38,2) AS total_story_points_bau,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) IS NULL THEN im.COMPLETED_POINTS ELSE 0 END)::NUMBER(38,2) AS total_story_points_work_type_empty
  FROM ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS im
  GROUP BY im.PROJECT_KEY,
         im.PROJECT_NAME,
         im.SPRINT_ID,
         im.SPRINT_NAME,
         im.SPRINT_NARRATIVE,
         im.EXECUTIVE_SUMMARY
)
SELECT bm.PROJECT_KEY,
       bm.PROJECT_NAME,
       bm.SPRINT_ID,
       bm.SPRINT_NARRATIVE,
       bm.EXECUTIVE_SUMMARY,
       bm.SPRINT_NAME,
       bm.TOTAL_POINTS,
       bm.TOTAL_TICKETS,
       bm.AVG_TICKET_SIZE,
       bm.TOTAL_STORY_POINTS,
       bm.TOTAL_STORY_TICKETS,
       bm.AVG_STORY_SIZE,
       bm.TOTAL_BUG_POINTS,
       bm.TOTAL_BUG_TICKETS,
       bm.AVG_BUG_SIZE,
       bm.TOTAL_TASK_POINTS,
       bm.TOTAL_TASK_TICKETS,
       bm.AVG_TASK_SIZE,
       bm.TOTAL_SPIKE_POINTS,
       bm.TOTAL_SPIKE_TICKETS,
       bm.AVG_SPIKE_SIZE,
       ZEROIFNULL(ROUND(AVG(bm.TOTAL_POINTS) OVER (PARTITION BY bm.PROJECT_KEY, ds.board_skey ORDER BY ds.SPRINT_COMPLETED_DATE ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2)) AS AVG_LAST_3_SPRINT_POINTS,
       bm.CARRY_OVER_TICKET,
       bm.CARRY_OVER_POINTS,
       COALESCE(wtm.TOTAL_TICKETS_PROJECT,0) AS TOTAL_TICKETS_PROJECT,
       COALESCE(wtm.TOTAL_TICKETS_KLO,0) AS TOTAL_TICKETS_KLO,
       COALESCE(wtm.TOTAL_TICKETS_BAU,0) AS TOTAL_TICKETS_BAU,
       COALESCE(wtm.TOTAL_TICKETS_WORK_TYPE_EMPTY,0) AS TOTAL_TICKETS_WORK_TYPE_EMPTY,
       COALESCE(wtm.TOTAL_STORY_POINTS_PROJECT,0) AS TOTAL_STORY_POINTS_PROJECT,
       COALESCE(wtm.TOTAL_STORY_POINTS_KLO,0) AS TOTAL_STORY_POINTS_KLO,
       COALESCE(wtm.TOTAL_STORY_POINTS_BAU,0) AS TOTAL_STORY_POINTS_BAU,
       COALESCE(wtm.TOTAL_STORY_POINTS_WORK_TYPE_EMPTY,0) AS TOTAL_STORY_POINTS_WORK_TYPE_EMPTY
FROM BASE_METRICS bm
  LEFT JOIN work_type_metrics wtm ON bm.SPRINT_ID = wtm.SPRINT_ID AND COALESCE (bm.SPRINT_NARRATIVE,'') = COALESCE (wtm.SPRINT_NARRATIVE,'') AND COALESCE (bm.EXECUTIVE_SUMMARY,'') = COALESCE (wtm.EXECUTIVE_SUMMARY,'') AND bm.PROJECT_NAME = wtm.PROJECT_NAME AND bm.PROJECT_KEY = wtm.PROJECT_KEY
  LEFT JOIN ${envId}_tz.agile_reporting.dim_sprint ds ON ds.SPRINT_ID = bm.SPRINT_ID AND ds.ACTIVE_FLAG = 1;

-- Grant Access to Views
grant select on VW_SPRINT_VELOCITY to role ANALYST;
