--liquibase formatted sql
--changeset manideep.madha@invitationhomes.com:EDCOR_835_updated_work_type_empty.sql


CREATE OR REPLACE VIEW VW_SPRINT_TARGET_AND_CHURN(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PLANNED_POINTS,
	COMPLETED_POINTS,
	COMPLETED_RATIO,
    TOTAL_STORY_POINTS_PROJECT,
    TOTAL_STORY_POINTS_KLO,
    TOTAL_STORY_POINTS_BAU,
    TOTAL_STORY_POINTS_WORK_TYPE_EMPTY,
	POINTS_ADDED,
	TICKETS_ADDED,
	POINTS_REMOVED,
	TICKETS_REMOVED,
	GROSS_POINT_CHURN,
	GROSS_TICKET_CHURN,
	NET_POINT_CHURN,
	NET_TICKET_CHURN,
	GROSS_POINT_CHURN_RATIO,
	NET_POINT_CHURN_RATIO,
	PLANNING_ACCURACY,
	CREATED_DATE,
	UPDATED_DATE
) as
WITH TOTAL_POINTS AS (
    SELECT DISTINCT
        IM.PROJECT_KEY AS PROJECT_KEY,
        IM.PROJECT_NAME AS PROJECT_NAME,
        IM.SPRINT_ID AS SPRINT_ID,
        IM.SPRINT_NAME AS SPRINT_NAME,
        SUM(IM.PLANNED_POINTS) OVER(PARTITION BY IM.SPRINT_ID) AS TOTAL_POINTS,
        SUM(IM.COMPLETED_POINTS) OVER(PARTITION BY IM.SPRINT_ID) AS COMPLETED_POINTS
    FROM ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM
    WHERE IM.BOARD_TYPE = 'Sprints'
),
AVG_LAST_3_SPRINT_POINTS AS (
    SELECT DISTINCT
        PROJECT_KEY,
        PROJECT_NAME,
        SPRINT_ID,
        SPRINT_NAME,
        TOTAL_POINTS,
        COMPLETED_POINTS,
        ZEROIFNULL(ROUND(AVG(TOTAL_POINTS) OVER (PARTITION BY PROJECT_KEY ORDER BY SPRINT_ID ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2)) AS AVG_LAST_3_SPRINT_POINTS
    FROM TOTAL_POINTS
),
WORK_TYPE_METRICS AS
(
  SELECT im.PROJECT_KEY,
         im.PROJECT_NAME,
         im.SPRINT_ID,
         im.SPRINT_NAME,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'project' THEN im.PLANNED_POINTS ELSE 0 END)::NUMBER(38,2) AS TOTAL_STORY_POINTS_PROJECT,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'klo' THEN im.PLANNED_POINTS ELSE 0 END)::NUMBER(38,2) AS TOTAL_STORY_POINTS_KLO,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) = 'bau' THEN im.PLANNED_POINTS ELSE 0 END)::NUMBER(38,2) AS TOTAL_STORY_POINTS_BAU,
         SUM(CASE WHEN LOWER(im.ISSUE_WORK_TYPE) is null THEN im.PLANNED_POINTS ELSE 0 END)::NUMBER(38,2) AS TOTAL_STORY_POINTS_WORK_TYPE_EMPTY
  FROM ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS im
  GROUP BY im.PROJECT_KEY,
         im.PROJECT_NAME,
         im.SPRINT_ID,
         im.SPRINT_NAME
)
SELECT DISTINCT
    IM.PROJECT_KEY,
    IM.PROJECT_NAME,
    IM.SPRINT_ID,
    IM.SPRINT_NAME,
    SP.TOTAL_POINTS AS PLANNED_POINTS,
    SP.COMPLETED_POINTS,
    ZEROIFNULL(SP.COMPLETED_POINTS/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS COMPLETED_RATIO,
    TOTAL_STORY_POINTS_PROJECT,
    TOTAL_STORY_POINTS_KLO,
    TOTAL_STORY_POINTS_BAU,
    TOTAL_STORY_POINTS_WORK_TYPE_EMPTY,
    SM.POINTS_ADDED,
    SM.TICKETS_ADDED,
    SM.POINTS_REMOVED,
    SM.TICKETS_REMOVED,
    SM.GROSS_POINT_CHURN,
    SM.GROSS_TICKET_CHURN,
    SM.NET_POINT_CHURN,
    SM.NET_TICKET_CHURN,
    ZEROIFNULL(SM.GROSS_POINT_CHURN/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS GROSS_POINT_CHURN_RATIO,
    ZEROIFNULL(SM.NET_POINT_CHURN/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS NET_POINT_CHURN_RATIO,
    ZEROIFNULL(SP.TOTAL_POINTS/NULLIFZERO(AVG_LAST_3_SPRINT_POINTS))::NUMBER(38,2) AS PLANNING_ACCURACY,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM
JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM ON IM.SPRINT_ID = SM.SPRINT_ID AND IM.PROJECT_KEY=SM.PROJECT_KEY
JOIN AVG_LAST_3_SPRINT_POINTS SP ON IM.SPRINT_ID = SP.SPRINT_ID AND IM.PROJECT_KEY=SP.PROJECT_KEY
JOIN WORK_TYPE_METRICS WT ON IM.SPRINT_ID=WT.SPRINT_ID AND IM.PROJECT_KEY=WT.PROJECT_KEY
ORDER BY SPRINT_ID
;

-- Grant Access to Views
grant select on VW_SPRINT_TARGET_AND_CHURN to role ANALYST;
