--liquibase formatted sql
--changeset manideep.madha@invitationhomes.com:EDCOR_835_update_backlog_health


CREATE OR REPLACE VIEW VW_BACKLOG_HEALTH(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	SPRINT_START_DATE,
	SPRINT_COMPLETED_DATE,
	READY_FOR_WORK_POINTS,
	FUTURE_SPRINTS,
	BACKLOG_HEALTH,
    TOTAL_TICKETS_PROJECT,
    TOTAL_TICKETS_KLO,
    TOTAL_TICKETS_BAU,
    TOTAL_STORY_POINTS_PROJECT,
    TOTAL_STORY_POINTS_KLO,
    TOTAL_STORY_POINTS_BAU
) as
WITH BASE_METRICS AS
(
  SELECT DISTINCT SM.PROJECT_KEY AS PROJECT_KEY,SM.BOARD_ID,
         SM.SPRINT_ID AS SPRINT_ID,
         SUM(CASE WHEN IM.COMPLETED_POINTS IS NOT NULL THEN IM.COMPLETED_POINTS ELSE 0 END) OVER (PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_POINTS
  FROM ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM
    LEFT JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM
           ON IM.SPRINT_ID = SM.SPRINT_ID
          AND IM.PROJECT_KEY = SM.PROJECT_KEY
  WHERE IM.BOARD_TYPE = 'Sprints'
),
AVG_LAST_3_SPRINT_POINTS AS
(
  SELECT PROJECT_KEY,
         SPRINT_ID,
         ZEROIFNULL(ROUND(AVG(TOTAL_POINTS) OVER (PARTITION BY PROJECT_KEY, BOARD_ID ORDER BY SPRINT_ID ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING),2)) AS AVG_LAST_3_SPRINT_POINTS
  FROM BASE_METRICS
)
SELECT BHM.PROJECT_KEY,
       BHM.PROJECT_NAME,
       BHM.SPRINT_ID,
       BHM.SPRINT_NAME,
       BHM.SPRINT_START_DATE,
       BHM.SPRINT_COMPLETED_DATE,
       BHM.READY_FOR_WORK_POINTS,
       BHM.FUTURE_SPRINTS,
       ROUND(CASE WHEN BHM.FUTURE_SPRINTS=0 THEN 0 ELSE ((BHM.READY_FOR_WORK_POINTS / NULLIFZERO (ALSP.AVG_LAST_3_SPRINT_POINTS)) / NULLIFZERO (BHM.FUTURE_SPRINTS)) END,1) AS BACKLOG_HEALTH,
       BHM.TOTAL_TICKETS_PROJECT,
       BHM.TOTAL_TICKETS_KLO,
       BHM.TOTAL_TICKETS_BAU,
       BHM.TOTAL_STORY_POINTS_PROJECT,
       BHM.TOTAL_STORY_POINTS_KLO,
       BHM.TOTAL_STORY_POINTS_BAU
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.BACKLOG_HEALTH_METRICS BHM
  LEFT JOIN AVG_LAST_3_SPRINT_POINTS ALSP ON BHM.SPRINT_ID = ALSP.SPRINT_ID AND BHM.PROJECT_KEY = ALSP.PROJECT_KEY;

-- Grant Access to Views
grant select on VW_BACKLOG_HEALTH to role ANALYST;
