--liquibase formatted sql
--changeset vivek.vadadoriya@invitationhomes.com:0131_TEAM_SIZE1.sql

CREATE OR REPLACE view VW_TEAM_SIZE(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PRODUCT_TEAM_SIZE,
	PRODUCT_DESIGN_TEAM_SIZE,
	DELIVERY_TEAM_SIZE,
	ENGINEERING_TEAM_SIZE,
	QUALITY_TEAM_SIZE,
	OTHER_TEAM_SIZE,
	TOTAL_ASSIGNED_TEAM_SIZE,
	EXECUTIVE_SUMMARY,
	SPRINT_NARRATIVE,
	CREATED_DATE,
	UPDATED_DATE
) as
SELECT 
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PRODUCT_TEAM_SIZE,
	PRODUCT_DESIGN_TEAM_SIZE,
	DELIVERY_TEAM_SIZE,
	ENGINEERING_TEAM_SIZE,
	QUALITY_TEAM_SIZE,
	OTHER_TEAM_SIZE,
	TOTAL_ASSIGNED_TEAM_SIZE,
	EXECUTIVE_SUMMARY,
	SPRINT_NARRATIVE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.QUICKBASE_METRICS
;

-- Grant Access to Views
grant select on VW_TEAM_SIZE to role ANALYST;
grant select on VW_TEAM_SIZE to role DEVELOPER;
