--liquibase formatted sql
--changeset vivek.vadadoriya@invitationhomes.com:0751_KANBAN_V1.sql

CREATE OR REPLACE VIEW VW_KANBAN(
PROJECT_KEY
, PROJECT_NAME
, WEEK
, YEAR
, FIRST_DAY_OF_WEEK
, AVG_LEAD_TIME
, AVG_BACKLOG_CYCLE_TIME
, AVG_KANBAN_CYCLE_TIME
, TIME_IN_OPEN
, TIME_IN_WORKING
, TIME_IN_QA
, THROUGHPUT
) AS
SELECT 
PROJECT_KEY
, PROJECT_NAME
, WEEK
, YEAR
, FIRST_DAY_OF_WEEK
, AVG_LEAD_TIME
, AVG_BACKLOG_CYCLE_TIME
, AVG_KANBAN_CYCLE_TIME
, TIME_IN_OPEN
, TIME_IN_WORKING
, TIME_IN_QA
, THROUGHPUT

FROM ${envId}_CZ.AGILE_REPORTING_MAIN.KANBAN_METRICS;

-- Grant Access to Views
grant select on VW_KANBAN to role ANALYST;
