--liquibase formatted sql

--changeset dhruv.bati@invitationhomes.com:0288_AGILE_ANALYSIS_DDL_V5.sql

create or replace view VW_BACKLOG_HEALTH(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	SPRINT_START_DATE,
	SPRINT_COMPLETED_DATE,
	READY_FOR_WORK_POINTS,
	FUTURE_SPRINTS,
	BACKLOG_HEALTH,
	CREATED_DATE,
	UPDATED_DATE
) as 
WITH BASE_METRICS AS (
    SELECT DISTINCT
        SM.PROJECT_KEY AS PROJECT_KEY,
        SM.SPRINT_ID AS SPRINT_ID,
        SUM(CASE WHEN IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_POINTS
    FROM ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM
    LEFT JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM ON IM.SPRINT_ID = SM.SPRINT_ID AND IM.PROJECT_KEY = SM.PROJECT_KEY
    WHERE IM.BOARD_TYPE = 'Sprints'
),
AVG_LAST_3_SPRINT_POINTS AS (
    SELECT
        PROJECT_KEY,
        SPRINT_ID,
        ZEROIFNULL(ROUND(AVG(TOTAL_POINTS) OVER (PARTITION BY PROJECT_KEY ORDER BY SPRINT_ID ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2)) AS AVG_LAST_3_SPRINT_POINTS
    FROM BASE_METRICS
)
SELECT
    BHM.PROJECT_KEY,
    BHM.PROJECT_NAME,
    BHM.SPRINT_ID,
    BHM.SPRINT_NAME,
    BHM.SPRINT_START_DATE,
    BHM.SPRINT_COMPLETED_DATE,
    BHM.READY_FOR_WORK_POINTS,
    BHM.FUTURE_SPRINTS,
    ROUND(((BHM.READY_FOR_WORK_POINTS/NULLIFZERO(ALSP.AVG_LAST_3_SPRINT_POINTS))/BHM.FUTURE_SPRINTS)*100,1) AS BACKLOG_HEALTH,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.BACKLOG_HEALTH_METRICS BHM
LEFT JOIN AVG_LAST_3_SPRINT_POINTS ALSP ON BHM.SPRINT_ID = ALSP.SPRINT_ID AND BHM.PROJECT_KEY = ALSP.PROJECT_KEY
;


create or replace view VW_KANBAN(
	PROJECT_KEY,
	PROJECT_NAME,
	WEEK,
	YEAR,
	FIRST_DAY_OF_WEEK,
	TOTAL_LEAD_TIME,
	AVG_BACKLOG_CYCLE_TIME,
	AVG_KANBAN_CYCLE_TIME,
	TIME_IN_OPEN,
	TIME_IN_WORKING,
	TIME_IN_QA,
	THROUGHPUT,
	CREATED_DATE,
	UPDATED_DATE
) as
select
    project_key,
    project_name,
    week,
    year,
    first_day_of_week,
    round(sum(total_lead_time),2) as total_lead_time,
    round(avg(total_open_to_working_time),2) as avg_backlog_cycle_time,
    round(avg(total_working_to_done_time),2) as avg_kanban_cycle_time,
    round(avg(open_status_time),2) as time_in_open,
    round(avg(working_status_time),2) as time_in_working,
    round(avg(qa_status_time),2) as time_in_qa,
    sum(case when issue_status = 'Done' then 1 else 0 end) as throughput,
	TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
	TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
from ${envId}_CZ.agile_reporting_main.kanban_metrics
group by all
;


create or replace view VW_KANBAN_STATUS(
	PROJECT_KEY,
	PROJECT_NAME,
	WEEK,
	YEAR,
	FIRST_DAY_OF_WEEK,
	ISSUE_STATUS,
	ISSUE_COUNT,
	CREATED_DATE,
	UPDATED_DATE
) as
select
    project_key,
    project_name,
    week,
    year,
    first_day_of_week,
    issue_status,
    count(issue_key) as issue_count,
	TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
	TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
from ${envId}_CZ.agile_reporting_main.kanban_metrics
group by all
;


create or replace view VW_SPRINT_TARGET_AND_CHURN(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PLANNED_POINTS,
	COMPLETED_POINTS,
	COMPLETED_RATIO,
	POINTS_ADDED,
	TICKETS_ADDED,
	POINTS_REMOVED,
	TICKETS_REMOVED,
	GROSS_POINT_CHURN,
	GROSS_TICKET_CHURN,
	NET_POINT_CHURN,
	NET_TICKET_CHURN,
	GROSS_POINT_CHURN_RATIO,
	NET_POINT_CHURN_RATIO,
	PLANNING_ACCURACY,
	CREATED_DATE,
	UPDATED_DATE
) as
WITH TOTAL_POINTS AS (
    SELECT DISTINCT
        IM.PROJECT_KEY AS PROJECT_KEY,
        IM.PROJECT_NAME AS PROJECT_NAME,
        IM.SPRINT_ID AS SPRINT_ID,
        IM.SPRINT_NAME AS SPRINT_NAME,
        SUM(IM.PLANNED_POINTS) OVER(PARTITION BY IM.SPRINT_ID, IM.PROJECT_KEY) AS TOTAL_POINTS,
        SUM(IM.COMPLETED_POINTS) OVER(PARTITION BY IM.SPRINT_ID, IM.PROJECT_KEY) AS COMPLETED_POINTS
    FROM ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM
    WHERE IM.BOARD_TYPE = 'Sprints'
),
AVG_LAST_3_SPRINT_POINTS AS (
    SELECT DISTINCT
        PROJECT_KEY,
        PROJECT_NAME,
        SPRINT_ID,
        SPRINT_NAME,
        TOTAL_POINTS,
        COMPLETED_POINTS,
        ZEROIFNULL(ROUND(AVG(COMPLETED_POINTS) OVER (PARTITION BY PROJECT_KEY ORDER BY SPRINT_ID ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2)) AS AVG_LAST_3_SPRINT_POINTS
    FROM TOTAL_POINTS
)
SELECT DISTINCT
    IM.PROJECT_KEY,
    IM.PROJECT_NAME,
    IM.SPRINT_ID,
    IM.SPRINT_NAME,
    SP.TOTAL_POINTS AS PLANNED_POINTS,
    SP.COMPLETED_POINTS,
    ZEROIFNULL(SP.COMPLETED_POINTS/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS COMPLETED_RATIO,
    SM.POINTS_ADDED,
    SM.TICKETS_ADDED,
    SM.POINTS_REMOVED,
    SM.TICKETS_REMOVED,
    SM.GROSS_POINT_CHURN,
    SM.GROSS_TICKET_CHURN,
    SM.NET_POINT_CHURN,
    SM.NET_TICKET_CHURN,
    ZEROIFNULL(SM.GROSS_POINT_CHURN/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS GROSS_POINT_CHURN_RATIO,
    ZEROIFNULL(SM.NET_POINT_CHURN/NULLIFZERO(SP.TOTAL_POINTS))::NUMBER(38,2) AS NET_POINT_CHURN_RATIO,
    ZEROIFNULL(SP.TOTAL_POINTS/NULLIFZERO(AVG_LAST_3_SPRINT_POINTS))::NUMBER(38,2) AS PLANNING_ACCURACY,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM
LEFT JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM ON IM.SPRINT_ID = SM.SPRINT_ID AND IM.PROJECT_KEY = SM.PROJECT_KEY
LEFT JOIN AVG_LAST_3_SPRINT_POINTS SP ON SM.SPRINT_ID = SP.SPRINT_ID AND SM.PROJECT_KEY = SP.PROJECT_KEY
WHERE IM.BOARD_TYPE = 'Sprints'
;


create or replace view VW_SPRINT_VELOCITY(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NARRATIVE,
	EXECUTIVE_SUMMARY,
	SPRINT_NAME,
	TOTAL_POINTS,
	TOTAL_TICKETS,
	AVG_TICKET_SIZE,
	TOTAL_STORY_POINTS,
	TOTAL_STORY_TICKETS,
	AVG_STORY_SIZE,
	TOTAL_BUG_POINTS,
	TOTAL_BUG_TICKETS,
	AVG_BUG_SIZE,
	TOTAL_TASK_POINTS,
	TOTAL_TASK_TICKETS,
	AVG_TASK_SIZE,
	TOTAL_SPIKE_POINTS,
	TOTAL_SPIKE_TICKETS,
	AVG_SPIKE_SIZE,
	AVG_LAST_3_SPRINT_POINTS,
    CARRY_OVER_TICKET,
    CARRY_OVER_POINTS,
	CREATED_DATE,
	UPDATED_DATE
) as
WITH BASE_METRICS AS (
    SELECT DISTINCT
        SM.PROJECT_KEY AS PROJECT_KEY,
        SM.PROJECT_NAME AS PROJECT_NAME,
        SM.SPRINT_ID AS SPRINT_ID,
        IM.SPRINT_NARRATIVE AS SPRINT_NARRATIVE,
        IM.EXECUTIVE_SUMMARY AS EXECUTIVE_SUMMARY,
        SM.SPRINT_NAME AS SPRINT_NAME,
        
        SUM(CASE WHEN IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_POINTS,
        SM.TOTAL_TICKETS AS TOTAL_TICKETS,
        ZEROIFNULL(TOTAL_POINTS/NULLIFZERO(SM.TOTAL_TICKETS))::NUMBER(38,2) AS AVG_TICKET_SIZE,
        
        SUM(CASE WHEN IM.ISSUE_TYPE = 'Story' AND IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_STORY_POINTS,
        SM.TOTAL_STORY_TICKETS AS TOTAL_STORY_TICKETS,
        ZEROIFNULL(TOTAL_STORY_POINTS/NULLIFZERO(SM.TOTAL_STORY_TICKETS))::NUMBER(38,2) AS AVG_STORY_SIZE,
        
        SUM(CASE WHEN IM.ISSUE_TYPE = 'Bug' AND IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_BUG_POINTS,
        SM.TOTAL_BUG_TICKETS AS TOTAL_BUG_TICKETS,
        ZEROIFNULL(TOTAL_BUG_POINTS/NULLIFZERO(SM.TOTAL_BUG_TICKETS))::NUMBER(38,2) AS AVG_BUG_SIZE,
    
        SUM(CASE WHEN IM.ISSUE_TYPE = 'Task' AND IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_TASK_POINTS,
        SM.TOTAL_TASK_TICKETS AS TOTAL_TASK_TICKETS,
        ZEROIFNULL(TOTAL_TASK_POINTS/NULLIFZERO(SM.TOTAL_TASK_TICKETS))::NUMBER(38,2) AS AVG_TASK_SIZE,
        
        SUM(CASE WHEN IM.ISSUE_TYPE = 'Spike' AND IM.ISSUE_STATUS = 'Done' THEN IM.COMPLETED_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS TOTAL_SPIKE_POINTS,
        SM.TOTAL_SPIKE_TICKETS AS TOTAL_SPIKE_TICKETS,
        ZEROIFNULL(TOTAL_SPIKE_POINTS/NULLIFZERO(SM.TOTAL_SPIKE_TICKETS))::NUMBER(38,2) AS AVG_SPIKE_SIZE,

        SUM(CASE WHEN IM.IS_CARRY_OVER THEN 1 ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS CARRY_OVER_TICKET,
        SUM(CASE WHEN IM.IS_CARRY_OVER THEN IM.STORY_POINTS ELSE 0 END) OVER(PARTITION BY SM.SPRINT_ID, SM.PROJECT_KEY) AS CARRY_OVER_POINTS
        
    FROM ${envId}_CZ.AGILE_REPORTING_MAIN.SPRINT_METRICS SM
    LEFT JOIN ${envId}_CZ.AGILE_REPORTING_MAIN.ISSUE_METRICS IM ON IM.SPRINT_ID = SM.SPRINT_ID AND SM.PROJECT_KEY = IM.PROJECT_KEY
    WHERE IM.BOARD_TYPE = 'Sprints'
)
SELECT
    PROJECT_KEY,
    PROJECT_NAME,
    SPRINT_ID,
    SPRINT_NARRATIVE,
    EXECUTIVE_SUMMARY,
    SPRINT_NAME,
    TOTAL_POINTS,
    TOTAL_TICKETS,
    AVG_TICKET_SIZE,
    TOTAL_STORY_POINTS,
    TOTAL_STORY_TICKETS,
    AVG_STORY_SIZE,
    TOTAL_BUG_POINTS,
    TOTAL_BUG_TICKETS,
    AVG_BUG_SIZE,
    TOTAL_TASK_POINTS,
    TOTAL_TASK_TICKETS,
    AVG_TASK_SIZE,
    TOTAL_SPIKE_POINTS,
    TOTAL_SPIKE_TICKETS,
    AVG_SPIKE_SIZE,
    ZEROIFNULL(ROUND(AVG(TOTAL_POINTS) OVER (PARTITION BY PROJECT_KEY ORDER BY SPRINT_ID ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING), 2)) AS AVG_LAST_3_SPRINT_POINTS,
    CARRY_OVER_TICKET,
    CARRY_OVER_POINTS,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM BASE_METRICS
;


create or replace view VW_TEAM_SIZE(
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PRODUCT_TEAM_SIZE,
	PRODUCT_DESIGN_TEAM_SIZE,
	DELIVERY_TEAM_SIZE,
	ENGINEERING_TEAM_SIZE,
	QUALITY_TEAM_SIZE,
	OTHER_TEAM_SIZE,
	TOTAL_ASSIGNED_TEAM_SIZE,
	EXECUTIVE_SUMMARY,
	SPRINT_NARRATIVE,
	CREATED_DATE,
	UPDATED_DATE
) as
SELECT 
	PROJECT_KEY,
	PROJECT_NAME,
	SPRINT_ID,
	SPRINT_NAME,
	PRODUCT_TEAM_SIZE,
	PRODUCT_DESIGN_TEAM_SIZE,
	DELIVERY_TEAM_SIZE,
	ENGINEERING_TEAM_SIZE,
	QUALITY_TEAM_SIZE,
	OTHER_TEAM_SIZE,
	TOTAL_ASSIGNED_TEAM_SIZE,
	EXECUTIVE_SUMMARY,
	SPRINT_NARRATIVE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS CREATED_DATE,
    TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP()) AS UPDATED_DATE
FROM ${envId}_CZ.AGILE_REPORTING_MAIN.QUICKBASE_METRICS;


-- Grant access to Views
grant select on VW_BACKLOG_HEALTH to role ANALYST;
grant select on VW_BACKLOG_HEALTH to role DEVELOPER;

grant select on VW_KANBAN to role ANALYST;
grant select on VW_KANBAN to role DEVELOPER;

grant select on VW_KANBAN_STATUS to role ANALYST;
grant select on VW_KANBAN_STATUS to role DEVELOPER;

grant select on VW_SPRINT_TARGET_AND_CHURN to role ANALYST;
grant select on VW_SPRINT_TARGET_AND_CHURN to role DEVELOPER;

grant select on VW_SPRINT_VELOCITY to role ANALYST;
grant select on VW_SPRINT_VELOCITY to role DEVELOPER;

grant select on VW_TEAM_SIZE to role ANALYST;
grant select on VW_TEAM_SIZE to role DEVELOPER;
