--liquibase formatted sql

--changeset vivek.vadadoriya@invitationhomes.com:0259_JIRA_RZ_DDL.sql

CREATE OR REPLACE TABLE JIRA_BOARD (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_FIX_VERSION (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_ISSUE (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_ISSUE_HISTORY (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_PROJECT (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_RELEASE (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE JIRA_SPRINT (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

grant select on JIRA_BOARD to role ANALYST;
grant select on JIRA_FIX_VERSION to role ANALYST;
grant select on JIRA_ISSUE to role ANALYST;
grant select on JIRA_ISSUE_HISTORY to role ANALYST;
grant select on JIRA_PROJECT to role ANALYST;
grant select on JIRA_RELEASE to role ANALYST;
grant select on JIRA_SPRINT to role ANALYST;