--liquibase formatted sql

--changeset vivek.vadadoriya@invitationhomes.com:0259_QUICKBASE_RZ_DDL.sql

CREATE OR REPLACE TABLE QB_SPRINT_REPORT (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);

CREATE OR REPLACE TABLE QB_TEAM_OVERVIEW_REPORT (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);


grant select on QB_SPRINT_REPORT to role ANALYST;
grant select on QB_TEAM_OVERVIEW_REPORT to role ANALYST;
