--liquibase formatted sql

--changeset manideep.madha@invitationhomes.com:0663_AGILE_JIRA_SPRINT_DETAILS_DDL.sql

CREATE OR REPLACE TABLE JIRA_SPRINT_DETAILS (
	BATCH_ID VARCHAR(100),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	RECORD VARIANT
);


grant select on JIRA_SPRINT_DETAILS to role ANALYST;