--liquibase formatted sql

--changeset vivek.vadadoriya@invitationhomes.com:0262_AGILE_RCZ_OBJECTS_DEVELOPER_GRANTS.sql



GRANT SELECT ON JIRA_BOARD TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_BOARD_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_FIX_VERSION TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_FIX_VERSION_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_ISSUE TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_ISSUE_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_ISSUE_HISTORY TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_ISSUE_HISTORY_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_PROJECT TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_PROJECT_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_RELEASE TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_RELEASE_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_SPRINT TO ROLE DEVELOPER;
GRANT SELECT ON JIRA_SPRINT_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON QB_SPRINT_REPORT TO ROLE DEVELOPER;
GRANT SELECT ON QB_SPRINT_REPORT_ERROR_LOG TO ROLE DEVELOPER;
GRANT SELECT ON QB_TEAM_OVERVIEW_REPORT TO ROLE DEVELOPER;
GRANT SELECT ON QB_TEAM_OVERVIEW_REPORT_ERROR_LOG TO ROLE DEVELOPER;