--liquibase formatted sql

--changeset vivek.vadadoriya@invitationhomes.com:0262_AGILE_RCZ_OBJECTS_GRANTS.sql

-- RCZ Tables

GRANT SELECT ON JIRA_BOARD TO ROLE ANALYST;
GRANT SELECT ON JIRA_BOARD_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_FIX_VERSION TO ROLE ANALYST;
GRANT SELECT ON JIRA_FIX_VERSION_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_ISSUE TO ROLE ANALYST;
GRANT SELECT ON JIRA_ISSUE_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_ISSUE_HISTORY TO ROLE ANALYST;
GRANT SELECT ON JIRA_ISSUE_HISTORY_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_PROJECT TO ROLE ANALYST;
GRANT SELECT ON JIRA_PROJECT_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_RELEASE TO ROLE ANALYST;
GRANT SELECT ON JIRA_RELEASE_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON JIRA_SPRINT TO ROLE ANALYST;
GRANT SELECT ON JIRA_SPRINT_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON QB_SPRINT_REPORT TO ROLE ANALYST;
GRANT SELECT ON QB_SPRINT_REPORT_ERROR_LOG TO ROLE ANALYST;
GRANT SELECT ON QB_TEAM_OVERVIEW_REPORT TO ROLE ANALYST;
GRANT SELECT ON QB_TEAM_OVERVIEW_REPORT_ERROR_LOG TO ROLE ANALYST;