--liquibase formatted sql

--changeset manideep.madha@invitationhomes.com:0663_AGILE_RCZ_JIRA_SPRINT_DETAILS_DDL.sql

create or replace TABLE JIRA_SPRINT_DETAILS (
	SPRINT_ID NUMBER(38,0),
	SPRINT_NAME VARCHAR(16777216),
	SPRINT_STATUS VARCHAR(16777216),
	SPRINT_BOARD_ID NUMBER(38,0),
	SPRINT_GOAL VARCHAR(16777216),
    SPRINT_CREATED_DATE TIMESTAMP_NTZ(9),
	SPRINT_START_DATE TIMESTAMP_NTZ(9),
	SPRINT_END_DATE TIMESTAMP_NTZ(9),
	SPRINT_COMPLETED_DATE TIMESTAMP_NTZ(9),
	INSERT_TIMESTAMP TIMESTAMP_NTZ(9),
	BATCH_ID VARCHAR(16777216)
);

create or replace TABLE JIRA_SPRINT_DETAILS_ERROR_LOG (
	SPRINT_ID NUMBER(38,0),
	SPRINT_NAME VARCHAR(16777216),
	SPRINT_STATUS VARCHAR(16777216),
	SPRINT_BOARD_ID NUMBER(38,0),
	SPRINT_GOAL VARCHAR(16777216),
    SPRINT_CREATED_DATE TIMESTAMP_NTZ(9),
	SPRINT_START_DATE TIMESTAMP_NTZ(9),
	SPRINT_END_DATE TIMESTAMP_NTZ(9),
	SPRINT_COMPLETED_DATE TIMESTAMP_NTZ(9),
	COMMENT VARCHAR(16777216),
	ETL_INSERTED_TIMESTAMP TIMESTAMP_NTZ(9),
	BATCH_ID VARCHAR(16777216)
);

GRANT SELECT ON JIRA_SPRINT_DETAILS TO ROLE ANALYST;
GRANT SELECT ON JIRA_SPRINT_DETAILS_ERROR_LOG TO ROLE ANALYST;
