name: ADHOC DML CHANGES WORKFLOW

on:
  workflow_dispatch:
    inputs:
      ServiceNow_CR:
        required: false
        type: string
        description: 'ServiceNow Change Request Number'
      ENV:
        required: true
        type: choice
        description: "environment"
        options:
          - "DEV"
          - "QA"
          - "PROD"
  
jobs:
  dev_dml_changes:
    runs-on: ubuntu-latest
    if: github.event.inputs.ENV == 'DEV' &&  github.event.inputs.ServiceNow_CR != ''
    steps:
      # Checkout the code with full history to detect file changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to ensure proper diff detection

      # Find the latest changed SQL file in the DML_CHANGES folder
      - name: Set executable permissions for the script
        run: chmod +x .github/workflows/workflow_scripts/fetch_changed_files_script.sh

      - name: Find latest changed sql files in DML_CHANGES
        id: get_sql_file
        run: |
            folders=("QUALITY/" "AUDIT/" "RZ/" "RCZ/" "TZ/" "CZ/" "SECURITY/" "MULESOFT/" "DATA_SHARE/" "WORK_FLOW_TEST/")
            file_extension=".sql"
            log_count=1
            GITHUB_JOB="dml"
            all_files=""

            for folder in "${folders[@]}"; do
            echo "Checking folder: $folder"
            changed_files=$(.github/workflows/workflow_scripts/fetch_changed_files_script.sh "$folder" "$file_extension" "$log_count" "$GITHUB_JOB" "dev")
            if [ -n "$changed_files" ]; then
                all_files+="$changed_files"$'\n'
            fi
            done

            if [ -z "$all_files" ]; then
                echo "No SQL file changes detected in DML_CHANGES folders."
                echo "sql_files=[]" >> $GITHUB_ENV
            else
                sql_files=$(echo "$all_files" | jq -R -s -c 'split("\n")[:-1]')
                echo "SQL files found: $sql_files"
                echo "sql_files=$sql_files" >> $GITHUB_ENV
            fi

      - name: Install python packages
        if: ${{ env.sql_files != '[]' }}
        run: |
          pip install snowflake-connector-python
      - name: Run Python Script
        if: ${{ env.sql_files != '[]' }}
        env:
          SNOWFLAKE_ACCOUNT: frhobru-ihqla01
          SNOWFLAKE_USERNAME: "asdasdasd"
          SNOWFLAKE_PASSWORD: "sadasdasd"
          SNOWFLAKE_WAREHOUSE: "asdasdasd"
          SNOWFLAKE_ROLE: SVC_ADHOC_DML_ROLE
          ADDED_FILES: ${{ env.sql_files }}
          ENV_VARIABLE: DEV
        run: |
          python .github/workflows/script/dml_changes_script.py ${{github.event.inputs.ServiceNow_CR}}